dbt_italy:

  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ env_var('CATALOG') }}"
      schema: "{{ env_var('SCHEMA') }}"
      host: "{{ env_var('HOST') }}"
      http_path: "{{ env_var('HTTP_PATH') }}"
      token: "{{ env_var('TOKEN') }}"
      threads: 1

elementary:
  outputs:
    default:
      type: databricks
      host: "{{ env_var('HOST') }}"
      http_path: "{{ env_var('HTTP_PATH') }}"
      catalog: bronze
      schema: elementary
      token: "{{ env_var('TOKEN') }}"
      threads: 1